// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: tests/servers/grpc/proto/mock.proto

package mock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_tests_servers_grpc_proto_mock_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_tests_servers_grpc_proto_mock_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_tests_servers_grpc_proto_mock_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ExecuteRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ExecuteRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_tests_servers_grpc_proto_mock_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TimeoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelaySeconds  int32                  `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutRequest) Reset() {
	*x = TimeoutRequest{}
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutRequest) ProtoMessage() {}

func (x *TimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutRequest.ProtoReflect.Descriptor instead.
func (*TimeoutRequest) Descriptor() ([]byte, []int) {
	return file_tests_servers_grpc_proto_mock_proto_rawDescGZIP(), []int{4}
}

func (x *TimeoutRequest) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

type TimeoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutResponse) Reset() {
	*x = TimeoutResponse{}
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutResponse) ProtoMessage() {}

func (x *TimeoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutResponse.ProtoReflect.Descriptor instead.
func (*TimeoutResponse) Descriptor() ([]byte, []int) {
	return file_tests_servers_grpc_proto_mock_proto_rawDescGZIP(), []int{5}
}

func (x *TimeoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_tests_servers_grpc_proto_mock_proto_rawDescGZIP(), []int{6}
}

func (x *EchoRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EchoRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *EchoRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tests_servers_grpc_proto_mock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_tests_servers_grpc_proto_mock_proto_rawDescGZIP(), []int{7}
}

func (x *EchoResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EchoResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *EchoResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_tests_servers_grpc_proto_mock_proto protoreflect.FileDescriptor

const file_tests_servers_grpc_proto_mock_proto_rawDesc = "" +
	"\n" +
	"#tests/servers/grpc/proto/mock.proto\x12\x04mock\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"b\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xbb\x01\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12;\n" +
	"\aheaders\x18\x03 \x03(\v2!.mock.ExecuteRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"5\n" +
	"\x0eTimeoutRequest\x12#\n" +
	"\rdelay_seconds\x18\x01 \x01(\x05R\fdelaySeconds\"+\n" +
	"\x0fTimeoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb5\x01\n" +
	"\vEchoRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x128\n" +
	"\aheaders\x18\x03 \x03(\v2\x1e.mock.EchoRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\fEchoResponse\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x129\n" +
	"\aheaders\x18\x03 \x03(\v2\x1f.mock.EchoResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa6\x02\n" +
	"\vMockService\x128\n" +
	"\vHealthCheck\x12\x13.mock.HealthRequest\x1a\x14.mock.HealthResponse\x126\n" +
	"\aExecute\x12\x14.mock.ExecuteRequest\x1a\x15.mock.ExecuteResponse\x12>\n" +
	"\rStreamExecute\x12\x14.mock.ExecuteRequest\x1a\x15.mock.ExecuteResponse0\x01\x126\n" +
	"\aTimeout\x12\x14.mock.TimeoutRequest\x1a\x15.mock.TimeoutResponse\x12-\n" +
	"\x04Echo\x12\x11.mock.EchoRequest\x1a\x12.mock.EchoResponseB6Z4github.com/VDHewei/xsh/tests/servers/grpc/proto;mockb\x06proto3"

var (
	file_tests_servers_grpc_proto_mock_proto_rawDescOnce sync.Once
	file_tests_servers_grpc_proto_mock_proto_rawDescData []byte
)

func file_tests_servers_grpc_proto_mock_proto_rawDescGZIP() []byte {
	file_tests_servers_grpc_proto_mock_proto_rawDescOnce.Do(func() {
		file_tests_servers_grpc_proto_mock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_servers_grpc_proto_mock_proto_rawDesc), len(file_tests_servers_grpc_proto_mock_proto_rawDesc)))
	})
	return file_tests_servers_grpc_proto_mock_proto_rawDescData
}

var file_tests_servers_grpc_proto_mock_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tests_servers_grpc_proto_mock_proto_goTypes = []any{
	(*HealthRequest)(nil),   // 0: mock.HealthRequest
	(*HealthResponse)(nil),  // 1: mock.HealthResponse
	(*ExecuteRequest)(nil),  // 2: mock.ExecuteRequest
	(*ExecuteResponse)(nil), // 3: mock.ExecuteResponse
	(*TimeoutRequest)(nil),  // 4: mock.TimeoutRequest
	(*TimeoutResponse)(nil), // 5: mock.TimeoutResponse
	(*EchoRequest)(nil),     // 6: mock.EchoRequest
	(*EchoResponse)(nil),    // 7: mock.EchoResponse
	nil,                     // 8: mock.ExecuteRequest.HeadersEntry
	nil,                     // 9: mock.EchoRequest.HeadersEntry
	nil,                     // 10: mock.EchoResponse.HeadersEntry
}
var file_tests_servers_grpc_proto_mock_proto_depIdxs = []int32{
	8,  // 0: mock.ExecuteRequest.headers:type_name -> mock.ExecuteRequest.HeadersEntry
	9,  // 1: mock.EchoRequest.headers:type_name -> mock.EchoRequest.HeadersEntry
	10, // 2: mock.EchoResponse.headers:type_name -> mock.EchoResponse.HeadersEntry
	0,  // 3: mock.MockService.HealthCheck:input_type -> mock.HealthRequest
	2,  // 4: mock.MockService.Execute:input_type -> mock.ExecuteRequest
	2,  // 5: mock.MockService.StreamExecute:input_type -> mock.ExecuteRequest
	4,  // 6: mock.MockService.Timeout:input_type -> mock.TimeoutRequest
	6,  // 7: mock.MockService.Echo:input_type -> mock.EchoRequest
	1,  // 8: mock.MockService.HealthCheck:output_type -> mock.HealthResponse
	3,  // 9: mock.MockService.Execute:output_type -> mock.ExecuteResponse
	3,  // 10: mock.MockService.StreamExecute:output_type -> mock.ExecuteResponse
	5,  // 11: mock.MockService.Timeout:output_type -> mock.TimeoutResponse
	7,  // 12: mock.MockService.Echo:output_type -> mock.EchoResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tests_servers_grpc_proto_mock_proto_init() }
func file_tests_servers_grpc_proto_mock_proto_init() {
	if File_tests_servers_grpc_proto_mock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_servers_grpc_proto_mock_proto_rawDesc), len(file_tests_servers_grpc_proto_mock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tests_servers_grpc_proto_mock_proto_goTypes,
		DependencyIndexes: file_tests_servers_grpc_proto_mock_proto_depIdxs,
		MessageInfos:      file_tests_servers_grpc_proto_mock_proto_msgTypes,
	}.Build()
	File_tests_servers_grpc_proto_mock_proto = out.File
	file_tests_servers_grpc_proto_mock_proto_goTypes = nil
	file_tests_servers_grpc_proto_mock_proto_depIdxs = nil
}
